version: '3'

services:
  testculture:
    build: .
    image: testculture
    restart: always
    environment:
        ASPNETCORE_ENVIRONMENT: "Production"
        ASPNETCORE_URLS: "http://*:80"
        ASPNETCORE_preventHostingStartup: "True"
    ports:
       - "8888:80"

  database:
     image: bitnami/postgresql:10
     restart: always
     environment:
         POSTGRESQL_USER: postgres
         POSTGRESQL_PASSWORD: password
         POSTGRESQL_DATABASE: postgres
     ports:
       - "5432:5432"
     volumes:
       - /root/database/postgresql:/bitnami/postgresql

